/*View data tables*/
Select *
From  BUDGET_FP
Select *
From TRANSACTION_FP
  ...
/*Drop unnecessary tables*/
ALTER TABLE BUDGET_FP
DROP COLUMN Short_CLASS;
ALTER TABLE TRANSACTION_FP
DROP COLUMN Short_CLASS;

--No of Clients--
SELECT COUNT(DISTINCT ACCOUNT) AS total_clients
FROM ACCOUNTS_FP;

--REVENUE TOTAL
SELECT  
  REVENUE_EXPENSES,
  SUM(AMOUNT) AS Revenue
FROM TRANSACTION_FP
WHERE REVENUE_EXPENSES = 'REVENUE'
GROUP BY REVENUE_EXPENSES
ORDER BY Revenue DESC;
--Expenses TOTAL_--
SELECT  
  REVENUE_EXPENSES,
  SUM(AMOUNT) AS Expenses
FROM TRANSACTION_FP
WHERE REVENUE_EXPENSES = 'Expenses'
GROUP BY REVENUE_EXPENSES
ORDER BY Expenses DESC;

--Actual Budget----
SELECT SUM(BUDGET) AS Total_budget
FROM BUDGET_FP;

--Revenue Trends over Time--
SELECT 
  YEAR(Date) AS Year,
  MONTH(Date) AS Month,
  SUM(Amount) AS MonthlyRevenue
FROM TRANSACTION_FP
WHERE REVENUE_EXPENSES= 'Revenue'
GROUP BY YEAR(Date), MONTH(Date)
ORDER BY Year, Month;

-- HIGHEST PAYING DEALS
SELECT 
  NAME,
  MAX(Amount) AS HighestPayment
FROM TRANSACTION_FP
WHERE REVENUE_EXPENSES = 'REVENUE'
GROUP BY NAME
ORDER BY HighestPayment DESC;

--TOP  SPENDING CATEGORIES/Transaction type Revenue
SELECT 
    TRANSACTION_TYPE,
    SUM(AMOUNT) AS Total_Amount
FROM 
    TRANSACTION_FP
GROUP BY 
    TRANSACTION_TYPE
ORDER BY 
    Total_Amount DESC;

--TOP 5 SPENDING VENDORS
SELECT TOP 5
 NAME,
  SUM(Amount) AS TOTAL_EXPENSES
FROM TRANSACTION_FP
WHERE REVENUE_EXPENSES = 'EXPENSES'
GROUP BY NAME
ORDER BY TOTAL_EXPENSES DESC;

--TOP 5 SPENDING CLIENTS BY ACCOUNT
SELECT TOP 5
 ACCOUNT,
  SUM(AMOUNT) AS CLIENTS_TOTAL_EXPENSES
FROM TRANSACTION_FP
WHERE REVENUE_EXPENSES = 'EXPENSES'
GROUP BY ACCOUNT
ORDER BY CLIENTS_TOTAL_EXPENSES DESC;

--TOP 5 SPENDING CLIENTS BY ACCOUNT REVENUE
SELECT TOP 5
 ACCOUNT,
  SUM(AMOUNT) AS CLIENTS_TOTAL_REVENUE
FROM TRANSACTION_FP
WHERE REVENUE_EXPENSES = 'REVENUE'
GROUP BY ACCOUNT
ORDER BY CLIENTS_TOTAL_REVENUE DESC;

-- SPENDING SPIKES--
SELECT 
  YEAR(Date) AS Year,
  MONTH(Date) AS Month,
  SUM(Amount) AS TotalSpending
FROM TRANSACTION_FP
WHERE TRANSACTION_TYPE = 'EXPENSE'
GROUP BY YEAR(Date), MONTH(Date)
ORDER BY TotalSpending DESC;
--MONTHLY REVENUE OVER THE YEARS--
SELECT 
  DATENAME(MONTH, Date) AS MonthName,
  SUM(Amount) AS TotalSpending
FROM TRANSACTION_FP
WHERE REVENUE_EXPENSES = 'REVENUE'
GROUP BY DATENAME(MONTH, Date), MONTH(Date)
ORDER BY TotalSpending ASC;

-- REVENUE BY SOURCE (CLASS)
SELECT 
    CLASS AS Revenue_Source,
    SUM(AMOUNT) AS Total_Revenue
FROM TRANSACTION_FP
WHERE [REVENUE_EXPENSES] = 'REVENUE'
GROUP BY CLASS
ORDER BY Total_Revenue DESC;
/*NET INCOME */
SELECT 
    SUM(CASE WHEN [REVENUE_EXPENSES] = 'REVENUE' THEN Amount ELSE 0 END) AS TotalRevenue,
    SUM(CASE WHEN [REVENUE_EXPENSES] = 'EXPENSES' THEN Amount ELSE 0 END) AS TotalExpenses,
    SUM(CASE WHEN [REVENUE_EXPENSES] = 'REVENUE' THEN Amount ELSE 0 END) - 
    SUM(CASE WHEN [REVENUE_EXPENSES] = 'EXPENSES' THEN Amount ELSE 0 END) AS TotalGrossProfit
FROM 
    TRANSACTION_FP;
/* Yearly Budget vs. Expenses Comparison*/
SELECT 
    YEAR(Date) AS Year,
    SUM(CASE WHEN TRANSACTION_TYPE = 'BUDGET' THEN Amount ELSE 0 END) AS TotalBudget,
    SUM(CASE WHEN TRANSACTION_TYPE = 'EXPENSE' THEN Amount ELSE 0 END) AS TotalExpenses,
    SUM(CASE WHEN TRANSACTION_TYPE = 'BUDGET' THEN Amount ELSE 0 END) - 
    SUM(CASE WHEN TRANSACTION_TYPE = 'EXPENSE' THEN Amount ELSE 0 END) AS NetDifference
FROM 
    TRANSACTION_FP
WHERE 
    TRANSACTION_TYPE IN ('BUDGET', 'EXPENSE')
    AND YEAR(Date) IN (2022, 2023, 2024) -- Filter for specific years
GROUP BY 
    YEAR(Date)
ORDER BY 
    Year DESC;

-- Yearly Budget Totals
SELECT 
    YEAR(Date) AS Year,
    SUM(BUDGET) AS AnnualBudget
FROM 
    BUDGET_FP
WHERE 
    YEAR(Date) BETWEEN 2022 AND 2024
GROUP BY 
    YEAR(Date)
ORDER BY 
    Year DESC;

--Yearly Expenses--
SELECT 
     YEAR(Date) AS Year,
	 SUM(Amount) As AnualExpenses
FROM
     TRANSACTION_FP
WHERE
    TRANSACTION_TYPE ='EXPENSE'
	AND YEAR(Date) BETWEEN 2022 AND 2024
GROUP BY
YEAR(Date)
ORDER BY
Year;
--Budget by class--
SELECT 
    CLASS,
    SUM(BUDGET) AS TOTAL_BUDGET
FROM 
    BUDGET_FP
GROUP BY 
    CLASS
ORDER BY 
    TOTAL_BUDGET DESC;
--EXPENSE BY CLASS
SELECT 
    CLASS,
    SUM(AMOUNT) AS TOTAL_EXPENSES
FROM 
    TRANSACTION_FP
WHERE 
    REVENUE_EXPENSES = 'EXPENSES'
GROUP BY 
    CLASS
ORDER BY 
    TOTAL_EXPENSES DESC;
 --ACTUAL BUDGET & EXPENSES BY CLASS--
SELECT 
    COALESCE(b.CLASS, e.CLASS) AS CLASS,
    b.TOTAL_BUDGET,
    e.TOTAL_EXPENSES,
    COALESCE(b.TOTAL_BUDGET, 0) - COALESCE(e.TOTAL_EXPENSES, 0) AS BALANCE
FROM
    (SELECT CLASS, SUM(BUDGET) AS TOTAL_BUDGET FROM BUDGET_FP GROUP BY CLASS) b
FULL JOIN
    (SELECT CLASS, SUM(AMOUNT) AS TOTAL_EXPENSES 
     FROM TRANSACTION_FP 
     WHERE REVENUE_EXPENSES = 'EXPENSES'
     GROUP BY CLASS) e
ON b.CLASS = e.CLASS
ORDER BY CLASS;

-- CLIENT TRANSACTION BREAKDOWN --
SELECT 
    NAME,
    COALESCE(SUM(CASE WHEN REVENUE_EXPENSES = 'EXPENSES' THEN AMOUNT END), 0) AS EXPENSES,
    COALESCE(SUM(CASE WHEN REVENUE_EXPENSES = 'REVENUE' THEN AMOUNT END), 0) AS REVENUE,
    COALESCE(SUM(CASE WHEN REVENUE_EXPENSES = 'REVENUE' THEN AMOUNT END), 0) - 
    COALESCE(SUM(CASE WHEN REVENUE_EXPENSES = 'EXPENSES' THEN AMOUNT END), 0) AS NET_INCOME
FROM 
    TRANSACTION_FP
GROUP BY 
    NAME
ORDER BY 
    NET_INCOME ASC;
--Budget Varience
SELECT 
    b.CLASS,
    b.TOTAL_BUDGET,
    e.TOTAL_EXPENSES,
    b.TOTAL_BUDGET - e.TOTAL_EXPENSES AS BUDGET_VARIANCE
FROM 
    (SELECT CLASS, SUM(BUDGET) AS TOTAL_BUDGET FROM BUDGET_FP GROUP BY CLASS) b
LEFT JOIN 
    (SELECT CLASS, SUM(AMOUNT) AS TOTAL_EXPENSES 
     FROM TRANSACTION_FP 
     WHERE REVENUE_EXPENSES = 'EXPENSES'
     GROUP BY CLASS) e
ON b.CLASS = e.CLASS
ORDER BY 
    b.TOTAL_BUDGET DESC;
--Budget variance %

--Gross Profit over the years--
SELECT 
    YEAR(Date) AS Year,
    SUM(CASE 
        WHEN REVENUE_EXPENSES = 'REVENUE' THEN Amount
        WHEN REVENUE_EXPENSES = 'EXPENSES' THEN -Amount
        ELSE 0 
    END) AS NetIncome
FROM 
    TRANSACTION_FP
WHERE 
    YEAR(Date) IN (2022, 2023, 2024)
    AND REVENUE_EXPENSES IN ('REVENUE', 'EXPENSES')
GROUP BY 
    YEAR(Date)
ORDER BY 
    Year;
--YEARLY INSIGHT ON BUDGET, EXPENSES & NETINCOME
SELECT 
    YEAR(Date) AS Year,
    SUM(CASE WHEN REVENUE_EXPENSES = 'REVENUE' THEN Amount ELSE 0 END) AS Revenue,
    SUM(CASE WHEN REVENUE_EXPENSES = 'EXPENSES' THEN Amount ELSE 0 END) AS Expenses,
    SUM(CASE WHEN REVENUE_EXPENSES = 'REVENUE' THEN Amount ELSE -Amount END) AS NetIncome
FROM 
    TRANSACTION_FP
WHERE 
    YEAR(Date) IN (2022, 2023, 2024)
GROUP BY 
    YEAR(Date)
ORDER BY 
    Year;
